### ISSUE TITLE
Broken changelog for windows

### ISSUE THREAD

**Issue by Kolobok12309** [release-it-plugins/lerna-changelog#130]
In windows environment i try use `release-it-lerna-changelog` and my changelogs in release looks something like [this](https://github.com/Kolobok12309/release-it-test/releases/tag/0.0.2) and in console this (It's different releases)
```
�🚀 Let's release release-it-test (currently at 0.0.2)


Changelog:
* Add lerna (bd2d34c)
* Remove lerna (69ad898)
* Update release script (e7bea72)
* Merge pull request #3 from Kolobok12309/feature/second-feature (0adb363)
* Add second console.log (0e182df)
```
---
Trouble in shell exec for windows, you try exec command `D:\projects\release-it-test\node_modules\lerna-changelog\bin\cli.js --next-version=Unreleased --from=0.0.2`, but windows try open `*.js` file by default viewer, for me it VSCode.
If call `node ...`, or `lerna-changelog --next-version=Unreleased --from=0.0.2` all fine.

**Comment by rwjblue** [comment]
Oh no, you are totally correct! I'm sorry about that.

Hmm, I'm not sure what is the correct way to find the executable in a platform agnostic way?

**Comment by Kolobok12309** [comment]
I can not suggest a completely correct option, but `lerna-changelog` without full path working correctly in windows, npm add `node_modules/.bin/lerna-changelog.cmd` and use it, for nix it `node_modules/.bin/lerna-changelog`.

I can help with tests for windows if needed.
