### ISSUE TITLE
Support release-it v17

### ISSUE THREAD

**Issue by jelhan** [release-it-plugins/lerna-changelog#297]
release-it [v17.0.0](https://github.com/release-it/release-it/releases/tag/17.0.0) was recently released. It is not supported by this plugin yet. Is it only a question of widening the peer dependency? Or are there any breaking changes in v17.0.0 requiring changes to this addon?

https://github.com/release-it-plugins/lerna-changelog/blob/d91bca4061fec1b291993c77709ced62a0f894d7/package.json#L53-L55

**Comment by jelhan** [comment]
Is addressed by #298.

**Comment by mkszepp** [comment]
It was added in release `6.1.0`
